# Dockerfile.python (shared base image)
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

# You can optionally pre-install common packages here
RUN pip install Django==4.2.17 python-dotenv==1.0.1 psycopg2-binary==2.9.10 requests==2.32.3 tzdata==2024.2 urllib3==2.3.0
