# Generated by Django 5.2.8 on 2025-11-22 02:29

import addons.base.models
import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import pathlib
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PureWindowsPath('C:/Users/Chad/OneDrive/Desktop/Python-Projects/GreenTechHub/private_media')), upload_to=addons.base.models.profile_avatar_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('avatar_url', models.URLField(blank=True)),
                ('avatar_source', models.CharField(blank=True, choices=[('upload', 'Upload'), ('google', 'Google'), ('github', 'GitHub'), ('none', 'None')], default='none', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
