# Generated by Django 4.2.17 on 2025-03-08 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapifyMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'mapify_marker',
            },
        ),
        migrations.CreateModel(
            name='MapifyMarkerIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=20)),
                ('prefix', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mapify_marker_icon',
            },
        ),
        migrations.CreateModel(
            name='MapifyPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mapify.mapifymarker')),
            ],
            options={
                'db_table': 'mapify_place',
            },
        ),
        migrations.AddConstraint(
            model_name='mapifymarkericon',
            constraint=models.UniqueConstraint(fields=('colour', 'icon', 'prefix'), name='unique_marker_icon', violation_error_message='A marker icon with this colour, icon, and prefix already exists.'),
        ),
        migrations.AddField(
            model_name='mapifymarker',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mapify.mapifymarkericon'),
        ),
        migrations.AddConstraint(
            model_name='mapifyplace',
            constraint=models.UniqueConstraint(fields=('link',), name='unique_marker', violation_error_message='A place with this link already exists.'),
        ),
    ]
